version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user_db_postgres
      POSTGRES_PASSWORD: my_secret_password_postgres
      POSTGRES_DB: antares_db